"""`braid wiki build`: genera wiki publicable desde DuckLake + Cognee.

AGENTS.md Prioridad B: wikis personales offline navegables (Astro Starlight).
Genera Markdown desde el DuckLake catalog y lo escribe en `.braid/wiki/`.
"""
from __future__ import annotations

import sys
from pathlib import Path

from ..paths import resolve_context


def _slugify(text: str) -> str:
    import re
    s = re.sub(r"[^a-zA-Z0-9]+", "-", text.lower()).strip("-")
    return s[:60].rstrip("-") or "page"


def _generate_adr_pages(cat, project_slug: str, wiki_dir: Path) -> list[str]:
    """Generate wiki pages from ADRs."""
    pages: list[str] = []
    try:
        adrs = cat.get_active_adrs()
    except Exception:
        return pages

    adrs_dir = wiki_dir / "adrs"
    adrs_dir.mkdir(parents=True, exist_ok=True)

    for adr in adrs:
        adr_id = str(adr.get("adr_id", adr.get("id", "?")))
        title = str(adr.get("title", "Untitled ADR"))
        status = str(adr.get("status", "Unknown"))
        context = str(adr.get("context", ""))
        decision = str(adr.get("decision", ""))

        slug = _slugify(f"{adr_id}-{title}")
        page_path = adrs_dir / f"{slug}.md"

        content = f"""# ADR {adr_id} — {title}

- **Status:** {status}
- **Project:** {project_slug}

## Context

{context or '(No context recorded)'}

## Decision

{decision or '(No decision recorded)'}

---

*Generated by `braid wiki build` from DuckLake catalog.*
"""
        page_path.write_text(content)
        pages.append(f"adrs/{slug}.md")

    return pages


def _generate_memory_pages(cat, project_slug: str, wiki_dir: Path) -> list[str]:
    """Generate wiki pages from project memory."""
    pages: list[str] = []

    # Project memory
    try:
        proj_mem = cat.search_project_memory("", project_slug=project_slug)
    except Exception:
        proj_mem = []

    if proj_mem:
        mem_dir = wiki_dir / "memory"
        mem_dir.mkdir(parents=True, exist_ok=True)

        # Group by memory_type
        by_type: dict[str, list] = {}
        for m in proj_mem:
            mt = str(m.get("memory_type", "other"))
            by_type.setdefault(mt, []).append(m)

        for mem_type, entries in by_type.items():
            slug = _slugify(mem_type)
            page_path = mem_dir / f"{slug}.md"

            lines = [f"# {mem_type.title()}\n"]
            lines.append(f"Project: **{project_slug}**\n")
            for e in entries:
                key = str(e.get("key", "?"))
                value = str(e.get("value", ""))
                lines.append(f"## {key}\n")
                lines.append(f"{value}\n")
                lines.append("---\n")

            page_path.write_text("\n".join(lines))
            pages.append(f"memory/{slug}.md")

    return pages


def _generate_kg_pages(cat, project_slug: str, wiki_dir: Path) -> list[str]:
    """Generate wiki pages from KG nodes."""
    pages: list[str] = []

    try:
        # Get a sample of nodes
        nodes = cat._q(
            f"SELECT node_id, node_type, name FROM {cat.alias}.kg_nodes "
            f"WHERE project_slug = '{project_slug}' LIMIT 100"
        )
    except Exception:
        return pages

    if not nodes:
        return pages

    kg_dir = wiki_dir / "knowledge-graph"
    kg_dir.mkdir(parents=True, exist_ok=True)

    # Group by type
    by_type: dict[str, list] = {}
    for n in nodes:
        ntype = str(n[1])
        by_type.setdefault(ntype, []).append({"id": str(n[0]), "name": str(n[2])})

    for ntype, entries in by_type.items():
        slug = _slugify(ntype)
        page_path = kg_dir / f"{slug}.md"

        lines = [f"# {ntype}\n"]
        lines.append(f"Project: **{project_slug}** | Count: **{len(entries)}**\n")
        for e in entries:
            lines.append(f"- `{e['name']}` (id: `{e['id']}`)")

        page_path.write_text("\n".join(lines))
        pages.append(f"knowledge-graph/{slug}.md")

    return pages


def _generate_index(wiki_dir: Path, project_slug: str, all_pages: list[str]) -> None:
    """Generate the wiki index page."""
    lines = [f"# {project_slug} — Wiki\n"]
    lines.append("Auto-generated by `braid wiki build`.\n")

    # Group pages by section
    sections: dict[str, list[str]] = {}
    for page in all_pages:
        section = page.split("/")[0] if "/" in page else "root"
        sections.setdefault(section, []).append(page)

    for section, pages in sorted(sections.items()):
        lines.append(f"## {section.title()}\n")
        for page in pages:
            name = page.rsplit("/", 1)[-1].removesuffix(".md")
            lines.append(f"- [{name}]({page})")
        lines.append("")

    (wiki_dir / "index.md").write_text("\n".join(lines))


def run(output_dir: str | None = None) -> int:
    ctx = resolve_context()
    wiki_dir = Path(output_dir) if output_dir else ctx.wiki_dir

    print(f"[braid wiki build] project={ctx.dataset_id} output={wiki_dir}")

    try:
        from ..ducklake import BraidCatalog
    except ImportError:
        print("[braid wiki build] DuckLake no disponible — no se puede generar wiki.", file=sys.stderr)
        return 1

    wiki_dir.mkdir(parents=True, exist_ok=True)
    all_pages: list[str] = []

    with BraidCatalog() as cat:
        all_pages.extend(_generate_adr_pages(cat, ctx.dataset_id, wiki_dir))
        all_pages.extend(_generate_memory_pages(cat, ctx.dataset_id, wiki_dir))
        all_pages.extend(_generate_kg_pages(cat, ctx.dataset_id, wiki_dir))

    _generate_index(wiki_dir, ctx.dataset_id, all_pages)

    print(f"[braid wiki build] generadas {len(all_pages)} páginas en {wiki_dir}")
    print("[braid wiki build] próximo paso: compilar con Astro Starlight (Mes 2+)")
    return 0
