"""`braid wiki build`: genera wiki publicable desde DuckLake + Cognee.

AGENTS.md Prioridad B: wikis personales offline navegables (Astro Starlight).
Genera Markdown desde el DuckLake catalog y lo escribe en `.braid/wiki/`.
"""
from __future__ import annotations

import shutil
import sys
from pathlib import Path

from ..paths import ProjectContext, resolve_context


def _slugify(text: str) -> str:
    import re
    s = re.sub(r"[^a-zA-Z0-9]+", "-", text.lower()).strip("-")
    return s[:60].rstrip("-") or "page"


def _generate_adr_pages(cat, project_slug: str, wiki_dir: Path) -> list[str]:
    """Generate wiki pages from ADRs."""
    pages: list[str] = []
    try:
        adrs = cat.get_active_adrs()
    except Exception:
        return pages

    adrs_dir = wiki_dir / "adrs"
    adrs_dir.mkdir(parents=True, exist_ok=True)

    for adr in adrs:
        adr_id = str(adr.get("adr_id", adr.get("id", "?")))
        title = str(adr.get("title", "Untitled ADR"))
        status = str(adr.get("status", "Unknown"))
        context = str(adr.get("context", ""))
        decision = str(adr.get("decision", ""))

        slug = _slugify(f"{adr_id}-{title}")
        page_path = adrs_dir / f"{slug}.md"

        content = f"""# ADR {adr_id} — {title}

- **Status:** {status}
- **Project:** {project_slug}

## Context

{context or '(No context recorded)'}

## Decision

{decision or '(No decision recorded)'}

---

*Generated by `braid wiki build` from DuckLake catalog.*
"""
        page_path.write_text(content)
        pages.append(f"adrs/{slug}.md")

    return pages


def _generate_memory_pages(cat, project_slug: str, wiki_dir: Path) -> list[str]:
    """Generate wiki pages from project memory."""
    pages: list[str] = []

    # Project memory
    try:
        proj_mem = cat.search_project_memory("", project_slug=project_slug)
    except Exception:
        proj_mem = []

    if proj_mem:
        mem_dir = wiki_dir / "memory"
        mem_dir.mkdir(parents=True, exist_ok=True)

        # Group by memory_type
        by_type: dict[str, list] = {}
        for m in proj_mem:
            mt = str(m.get("memory_type", "other"))
            by_type.setdefault(mt, []).append(m)

        for mem_type, entries in by_type.items():
            slug = _slugify(mem_type)
            page_path = mem_dir / f"{slug}.md"

            lines = [f"# {mem_type.title()}\n"]
            lines.append(f"Project: **{project_slug}**\n")
            for e in entries:
                key = str(e.get("key", "?"))
                value = str(e.get("value", ""))
                lines.append(f"## {key}\n")
                lines.append(f"{value}\n")
                lines.append("---\n")

            page_path.write_text("\n".join(lines))
            pages.append(f"memory/{slug}.md")

    return pages


def _generate_kg_pages(cat, project_slug: str, wiki_dir: Path) -> list[str]:
    """Generate wiki pages from KG nodes."""
    pages: list[str] = []

    try:
        # Get a sample of nodes
        nodes = cat._q(
            f"SELECT node_id, node_type, name FROM {cat.alias}.kg_nodes "
            f"WHERE project_slug = '{project_slug}' LIMIT 100"
        )
    except Exception:
        return pages

    if not nodes:
        return pages

    kg_dir = wiki_dir / "knowledge-graph"
    kg_dir.mkdir(parents=True, exist_ok=True)

    # Group by type
    by_type: dict[str, list] = {}
    for n in nodes:
        ntype = str(n[1])
        by_type.setdefault(ntype, []).append({"id": str(n[0]), "name": str(n[2])})

    for ntype, entries in by_type.items():
        slug = _slugify(ntype)
        page_path = kg_dir / f"{slug}.md"

        lines = [f"# {ntype}\n"]
        lines.append(f"Project: **{project_slug}** | Count: **{len(entries)}**\n")
        for e in entries:
            lines.append(f"- `{e['name']}` (id: `{e['id']}`)")

        page_path.write_text("\n".join(lines))
        pages.append(f"knowledge-graph/{slug}.md")

    return pages


def _generate_index(wiki_dir: Path, project_slug: str, all_pages: list[str]) -> None:
    """Generate the wiki index page."""
    lines = [f"# {project_slug} — Wiki\n"]
    lines.append("Auto-generated by `braid wiki build`.\n")

    # Group pages by section
    sections: dict[str, list[str]] = {}
    for page in all_pages:
        section = page.split("/")[0] if "/" in page else "root"
        sections.setdefault(section, []).append(page)

    for section, pages in sorted(sections.items()):
        lines.append(f"## {section.title()}\n")
        for page in pages:
            name = page.rsplit("/", 1)[-1].removesuffix(".md")
            lines.append(f"- [{name}]({page})")
        lines.append("")

    (wiki_dir / "index.md").write_text("\n".join(lines))


def _safe_dataset_dir(dataset_id: str) -> str:
    name = dataset_id.replace("/", "-").replace("\\", "-").strip()
    return name or "project"


def _copy_markdown_file(src: Path, dest: Path, fallback_title: str) -> bool:
    dest.parent.mkdir(parents=True, exist_ok=True)
    if src.is_file():
        shutil.copyfile(src, dest)
        return True
    dest.write_text(f"# {fallback_title}\n\n(No source file found.)\n")
    return False


def _copy_markdown_tree(src_dir: Path, dest_dir: Path) -> list[str]:
    copied: list[str] = []
    if not src_dir.is_dir():
        dest_dir.mkdir(parents=True, exist_ok=True)
        return copied
    for src in sorted(src_dir.glob("*.md")):
        dest = dest_dir / src.name
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, dest)
        copied.append(str(dest.relative_to(dest_dir.parent)))
    return copied


def _obsidian_link(path: str) -> str:
    return path.removesuffix(".md")


def _obsidian_target(ctx: ProjectContext, output_dir: str | None, vault_dir: str | None) -> tuple[Path, bool]:
    if output_dir and vault_dir:
        raise ValueError("--output and --vault are mutually exclusive")
    if vault_dir:
        vault = Path(vault_dir).expanduser().resolve()
        return vault / "Braid" / _safe_dataset_dir(ctx.dataset_id), False
    if output_dir:
        return Path(output_dir).expanduser().resolve(), True
    return ctx.wiki_dir / "obsidian", True


def _ensure_obsidian_vault(vault_root: Path, create_settings: bool) -> None:
    vault_root.mkdir(parents=True, exist_ok=True)
    if create_settings:
        (vault_root / ".obsidian").mkdir(parents=True, exist_ok=True)


def _generate_obsidian_catalog_pages(ctx: ProjectContext, vault_root: Path) -> tuple[list[str], str]:
    generated_dir = vault_root / "Generated"
    try:
        from ..ducklake import BraidCatalog
    except ImportError as exc:
        return [], f"DuckLake unavailable: {exc}"

    try:
        generated_dir.mkdir(parents=True, exist_ok=True)
        pages: list[str] = []
        with BraidCatalog() as cat:
            pages.extend(_generate_adr_pages(cat, ctx.dataset_id, generated_dir))
            pages.extend(_generate_memory_pages(cat, ctx.dataset_id, generated_dir))
            pages.extend(_generate_kg_pages(cat, ctx.dataset_id, generated_dir))
        if pages:
            _generate_index(generated_dir, ctx.dataset_id, pages)
        return [f"Generated/{page}" for page in pages], f"generated {len(pages)} catalog pages"
    except Exception as exc:
        return [], f"DuckLake skipped: {exc}"


def _write_obsidian_home(
    ctx: ProjectContext,
    vault_root: Path,
    memory_exported: bool,
    adr_pages: list[str],
    plan_pages: list[str],
    generated_pages: list[str],
    catalog_status: str,
) -> None:
    lines = [
        "# Braid Home",
        "",
        f"- **Project:** {ctx.dataset_id}",
        f"- **Root:** `{ctx.root}`",
        f"- **State:** `{ctx.braid_dir}`",
        f"- **Canonical memory:** `{ctx.memory_dir}`",
        "",
        "## Navigation",
        "",
        f"- [[{_obsidian_link('Memory/MEMORY.md')}|Project Memory]]",
    ]
    if adr_pages:
        lines.append("- ADRs")
        for page in adr_pages:
            lines.append(f"  - [[{_obsidian_link(page)}]]")
    if plan_pages:
        lines.append("- Plans")
        for page in plan_pages:
            lines.append(f"  - [[{_obsidian_link(page)}]]")
    if generated_pages:
        lines.append("- Generated Catalog Pages")
        for page in generated_pages:
            lines.append(f"  - [[{_obsidian_link(page)}]]")

    lines.extend(
        [
            "",
            "## Commands",
            "",
            "- `braid status --json`",
            "- `braid doctor`",
            "- `braid patterns`",
            "- `braid wiki build --obsidian`",
            "",
            "## Export Status",
            "",
            f"- Memory source copied: `{str(memory_exported).lower()}`",
            f"- Catalog: {catalog_status}",
            "",
            "> This vault is a generated reading surface. The source of truth remains Braid memory.",
            "",
        ]
    )
    (vault_root / "Braid Home.md").write_text("\n".join(lines))


def _run_obsidian(ctx: ProjectContext, output_dir: str | None, vault_dir: str | None) -> int:
    try:
        vault_root, create_settings = _obsidian_target(ctx, output_dir, vault_dir)
    except ValueError as exc:
        print(f"[braid wiki build] {exc}", file=sys.stderr)
        return 2

    _ensure_obsidian_vault(vault_root, create_settings=create_settings)

    memory_exported = _copy_markdown_file(
        ctx.memory_dir / "MEMORY.md",
        vault_root / "Memory" / "MEMORY.md",
        "Project Memory",
    )
    adr_pages = _copy_markdown_tree(ctx.memory_dir / "decisions", vault_root / "ADRs")
    plan_pages = _copy_markdown_tree(ctx.memory_dir / "plans", vault_root / "Plans")
    try:
        generated_pages, catalog_status = _generate_obsidian_catalog_pages(ctx, vault_root)
    except Exception as exc:
        generated_pages, catalog_status = [], f"DuckLake skipped: {exc}"

    _write_obsidian_home(
        ctx,
        vault_root,
        memory_exported=memory_exported,
        adr_pages=adr_pages,
        plan_pages=plan_pages,
        generated_pages=generated_pages,
        catalog_status=catalog_status,
    )

    total = 2 + len(adr_pages) + len(plan_pages) + len(generated_pages)
    print(f"[braid wiki build] obsidian project={ctx.dataset_id} output={vault_root}")
    print(f"[braid wiki build] Obsidian notes generated: {total}")
    print(f"[braid wiki build] {catalog_status}")
    return 0


def run(output_dir: str | None = None, obsidian: bool = False, vault_dir: str | None = None) -> int:
    ctx = resolve_context()
    if vault_dir and not obsidian:
        print("[braid wiki build] --vault requires --obsidian", file=sys.stderr)
        return 2
    if obsidian:
        return _run_obsidian(ctx, output_dir=output_dir, vault_dir=vault_dir)

    wiki_dir = Path(output_dir) if output_dir else ctx.wiki_dir

    print(f"[braid wiki build] project={ctx.dataset_id} output={wiki_dir}")

    try:
        from ..ducklake import BraidCatalog
    except ImportError:
        print("[braid wiki build] DuckLake no disponible — no se puede generar wiki.", file=sys.stderr)
        return 1

    wiki_dir.mkdir(parents=True, exist_ok=True)
    all_pages: list[str] = []

    with BraidCatalog() as cat:
        all_pages.extend(_generate_adr_pages(cat, ctx.dataset_id, wiki_dir))
        all_pages.extend(_generate_memory_pages(cat, ctx.dataset_id, wiki_dir))
        all_pages.extend(_generate_kg_pages(cat, ctx.dataset_id, wiki_dir))

    _generate_index(wiki_dir, ctx.dataset_id, all_pages)

    print(f"[braid wiki build] generadas {len(all_pages)} páginas en {wiki_dir}")
    print("[braid wiki build] próximo paso: compilar con Astro Starlight (Mes 2+)")
    return 0
